# Generated by Django 5.2.15 on 2026-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectGallery", "0003_auto_20200517_0236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
