# Generated by Django 5.2.15 on 2026-07-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='imdb_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
