# Generated by Django 5.2.15 on 2026-07-29 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0002_alter_activity_imdb_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['user', 'group'], name='movie_night_user_id_8b0716_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='movie_night_user_id_bb0883_idx'),
        ),
    ]
