# Generated by Django 5.2.15 on 2026-07-29 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0003_availabilityslot_movie_night_user_id_8b0716_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityinterest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='activityinterest',
            constraint=models.UniqueConstraint(fields=('user', 'activity'), name='unique_activity_interest'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_group_member'),
        ),
    ]
