# Generated by Django 3.0.6 on 2020-05-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dndClass', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(max_length=255)),
                ('alignment', models.CharField(max_length=255)),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('eyes', models.CharField(blank=True, max_length=255, null=True)),
                ('skin', models.CharField(blank=True, max_length=255, null=True)),
                ('hair', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('proficiencyBonus', models.IntegerField()),
                ('inspiration', models.IntegerField(blank=True, null=True)),
                ('ac', models.IntegerField()),
                ('initiative', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField()),
                ('currentHP', models.IntegerField()),
                ('tempHP', models.CharField(blank=True, max_length=255, null=True)),
                ('hitDiceType', models.CharField(max_length=255)),
                ('hitDice', models.CharField(max_length=255)),
                ('personalityNotes', models.TextField(blank=True, null=True)),
                ('proficienciesNotes', models.TextField(blank=True, null=True)),
                ('equipmentNotes', models.TextField(blank=True, null=True)),
                ('alliesNotes', models.TextField(blank=True, null=True)),
                ('backstoryNotes', models.TextField(blank=True, null=True)),
                ('additionalNotes', models.TextField(blank=True, null=True)),
                ('treasureNotes', models.TextField(blank=True, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('sp', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('ep', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField(blank=True, null=True)),
                ('spellcastingClass', models.CharField(blank=True, max_length=255, null=True)),
                ('spellcastingAbility', models.CharField(blank=True, max_length=255, null=True)),
                ('lvl1slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl1slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl2slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl2slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl3slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl3slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl4slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl4slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl5slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl5slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl6slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl6slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl7slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl7slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl8slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl8slotsUsed', models.IntegerField(blank=True, null=True)),
                ('lvl9slotsTotal', models.IntegerField(blank=True, null=True)),
                ('lvl9slotsUsed', models.IntegerField(blank=True, null=True)),
                ('campaignJournal', models.TextField(blank=True, null=True)),
                ('externalReferences', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeType', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('longDescription', models.TextField(blank=True, null=True)),
                ('orderindex', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=255)),
                ('templateName', models.CharField(max_length=255)),
                ('orderindex', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customPages', to='naga.Character')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fieldValue', models.CharField(max_length=255)),
                ('parentStat', models.CharField(max_length=255)),
                ('isProficient', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='naga.Character')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naga.Node')),
                ('damage', models.CharField(max_length=255)),
                ('abilityModifier', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaponNodes', to='naga.Character')),
            ],
            bases=('naga.node',),
        ),
        migrations.CreateModel(
            name='SpellNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naga.Node')),
                ('prepared', models.BooleanField()),
                ('level', models.IntegerField()),
                ('dndClass', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spellNodes', to='naga.Character')),
            ],
            bases=('naga.node',),
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naga.Node')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillNodes', to='naga.Character')),
            ],
            bases=('naga.node',),
        ),
    ]
