# Generated by Django 3.0.6 on 2020-05-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingThrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fieldValue', models.CharField(max_length=255)),
                ('isProficient', models.BooleanField(default=False)),
                ('orderindex', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savingThrows', to='naga.Character')),
            ],
        ),
    ]
