# Generated by Django 3.0.6 on 2020-05-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naga', '0002_savingthrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='nodeType',
        ),
    ]
