# Generated by Django 3.0.6 on 2020-05-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naga', '0003_remove_node_nodetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='miscWeaponNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
