# Generated by Django 3.0.6 on 2020-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naga', '0004_character_miscweaponnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='useSpellPage',
            field=models.BooleanField(default=True),
        ),
    ]
