# Generated by Django 3.0.6 on 2020-05-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naga', '0006_auto_20200517_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='weaponNotes',
            new_name='weaponsNotes',
        ),
    ]
