# Generated by Django 3.0.6 on 2020-05-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naga', '0008_auto_20200517_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithtext',
            name='displayName',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
