# Generated by Django 4.2.23 on 2025-06-20 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naga', '0010_auto_20200517_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='dndClass',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spellcastingAbility',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spellcastingClass',
        ),
        migrations.RemoveField(
            model_name='spellnode',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='lvl0slotsTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl0slotsUsed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='statusNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingthrow',
            name='parentStat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spellnode',
            name='areaOfEffect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='areaShape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='castingTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='components',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='concentration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='dataSource',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='htmlDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='lists',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='meleeSpellAttack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='meleeWeaponAttack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='pageNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='rangedSpellAttack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='rangedWeaponAttack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='ritual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spellnode',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weaponnode',
            name='proficient',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abilityscore',
            name='fieldValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='ac',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='headshot',
            field=models.ImageField(blank=True, default='naga/blankUser.png', null=True, upload_to='naga/uploads/characterHeadshots/'),
        ),
        migrations.AlterField(
            model_name='imagewithtext',
            name='image',
            field=models.ImageField(default='naga/blankUser.png', upload_to='naga/uploads/imageWithText/'),
        ),
        migrations.AlterField(
            model_name='savingthrow',
            name='fieldValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DndClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Rogue'), ('2', 'Wizard'), ('3', 'Bard'), ('4', 'Artificer'), ('5', 'Fighter'), ('6', 'Druid'), ('7', 'Monk'), ('8', 'Warlock')], max_length=20, unique=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('isPrimaryAtkClass', models.BooleanField(default=False)),
                ('isPrimarySpellClass', models.BooleanField(default=False)),
                ('isSpellcastingClass', models.BooleanField(default=False)),
                ('shortRestSlotsTotal', models.IntegerField(blank=True, null=True)),
                ('shortRestSlotsUsed', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dndClasses', to='naga.character')),
            ],
        ),
        migrations.AlterField(
            model_name='spellnode',
            name='dndClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spellNodes', to='naga.dndclass'),
        ),
    ]
